CREATE DATABASE IF NOT EXISTS nebula_library;

USE nebula_library;

CREATE TABLE users(

id INT AUTO_INCREMENT PRIMARY KEY,

full_name VARCHAR(100) NOT NULL,

email VARCHAR(100) UNIQUE NOT NULL,

phone VARCHAR(15),

password VARCHAR(255) NOT NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);